export const ADVANCED_TOOLS=["MSA","DOE","FAULT_TREE","BOWTIE","RCM","TRIZ","TOYOTA_KATA","CAUSAL_LOOP"] as const;
export type AdvancedTool=(typeof ADVANCED_TOOLS)[number];
export interface AdvancedAnalysis { id:string; tool:AdvancedTool; title:string; status:"DRAFT"|"IN_PROGRESS"|"REVIEW"|"COMPLETED"; decisionPoint:string; hypothesis:string; fields:Record<string,string>; rows:Record<string,string>[]; conclusion:string; evidenceIds:string[] }
export interface AdvancedToolDefinition { name:string; purpose:string; fields:{key:string;label:string}[]; columns:{key:string;label:string}[] }
export const ADVANCED_TOOL_DEFINITIONS:Record<AdvancedTool,AdvancedToolDefinition>={
  MSA:{name:"Measurement System Analysis",purpose:"Ölçüm varyasyonunu proses varyasyonundan ayır.",fields:[{key:"tolerance",label:"Tolerans genişliği"},{key:"acceptance",label:"Kabul sınırı (%)"}],columns:[{key:"part",label:"Parça"},{key:"appraiser",label:"Ölçen"},{key:"trial",label:"Tekrar"},{key:"value",label:"Ölçüm"}]},
  DOE:{name:"Design of Experiments",purpose:"Faktör etkilerini kontrollü deneyle ayır.",fields:[{key:"response",label:"Yanıt değişkeni"},{key:"objective",label:"Optimizasyon amacı"}],columns:[{key:"factorA",label:"Faktör A (-1/+1)"},{key:"factorB",label:"Faktör B (-1/+1)"},{key:"response",label:"Yanıt"}]},
  FAULT_TREE:{name:"Fault Tree Analysis",purpose:"Tepe olayını mantıksal alt olaylara ayrıştır.",fields:[{key:"topEvent",label:"Tepe olay"},{key:"targetProbability",label:"Hedef olasılık"}],columns:[{key:"event",label:"Alt olay"},{key:"gate",label:"Kapı (AND/OR)"},{key:"probability",label:"Olasılık (0-1)"}]},
  BOWTIE:{name:"Bowtie Barrier Analysis",purpose:"Tehdit–tepe olay–sonuç zincirindeki bariyerleri doğrula.",fields:[{key:"hazard",label:"Tehlike"},{key:"topEvent",label:"Tepe olay"}],columns:[{key:"side",label:"PREVENTIVE/MITIGATIVE"},{key:"threatOrConsequence",label:"Tehdit / sonuç"},{key:"barrier",label:"Bariyer"},{key:"status",label:"EFFECTIVE/WEAK/MISSING"},{key:"owner",label:"Sahip"}]},
  RCM:{name:"Reliability-Centered Maintenance",purpose:"Arıza etkisine uygun bakım politikasını seç.",fields:[{key:"asset",label:"Varlık / ekipman"},{key:"function",label:"Fonksiyon"}],columns:[{key:"failureMode",label:"Arıza modu"},{key:"severity",label:"Şiddet 1-10"},{key:"occurrence",label:"Oluşma 1-10"},{key:"detectability",label:"Tespit 1-10"},{key:"task",label:"Bakım görevi"},{key:"interval",label:"Periyot"}]},
  TRIZ:{name:"TRIZ",purpose:"Teknik çelişkiyi ödün vermeden çözüm prensiplerine dönüştür.",fields:[{key:"improving",label:"İyileştirilecek özellik"},{key:"worsening",label:"Kötüleşen özellik"},{key:"idealFinal",label:"İdeal nihai sonuç"}],columns:[{key:"principle",label:"TRIZ prensibi"},{key:"concept",label:"Çözüm kavramı"},{key:"test",label:"Doğrulama deneyi"}]},
  TOYOTA_KATA:{name:"Toyota Kata",purpose:"Belirsiz hedefe kısa öğrenme deneyleriyle ilerle.",fields:[{key:"challenge",label:"Uzun vadeli meydan okuma"},{key:"current",label:"Mevcut durum"},{key:"target",label:"Hedef koşul"},{key:"obstacle",label:"Şu anki engel"}],columns:[{key:"experiment",label:"Sonraki adım / deney"},{key:"expected",label:"Beklenen"},{key:"actual",label:"Gerçekleşen"},{key:"learned",label:"Öğrenilen"},{key:"date",label:"Tarih"}]},
  CAUSAL_LOOP:{name:"Causal Loop / Systems Thinking",purpose:"Geri besleme döngülerini ve gecikmeleri görünür kıl.",fields:[{key:"systemBoundary",label:"Sistem sınırı"},{key:"behaviorOverTime",label:"Zaman içindeki davranış"}],columns:[{key:"from",label:"Nedenden"},{key:"to",label:"Sonuca"},{key:"polarity",label:"+/−"},{key:"delay",label:"Gecikme"},{key:"evidence",label:"Kanıt"}]},
};
const n=(v:string|undefined)=>Number(v);
export function evaluateAdvancedAnalysis(a:AdvancedAnalysis) {
  const def=ADVANCED_TOOL_DEFINITIONS[a.tool]; const missing=def.fields.filter(f=>!(a.fields[f.key]??"").trim()).map(f=>f.label); if(!a.decisionPoint.trim())missing.push("Karar noktası");if(!a.hypothesis.trim())missing.push("Hipotez / soru");if(!a.conclusion.trim())missing.push("Sonuç");if(!a.evidenceIds.length)missing.push("Bağlı kanıt");let metric=""; let warning="";
  if(a.tool==="MSA"){const values=a.rows.map(r=>n(r.value)).filter(Number.isFinite);const range=values.length?Math.max(...values)-Math.min(...values):0;const groups=new Map<string,number[]>();a.rows.forEach(r=>{const v=n(r.value);if(Number.isFinite(v)){const k=`${r.part}|${r.appraiser}`;groups.set(k,[...(groups.get(k)??[]),v])}});const repeat=[...groups.values()].filter(x=>x.length>1).map(x=>Math.max(...x)-Math.min(...x));const rr=repeat.length?repeat.reduce((s,x)=>s+x,0)/repeat.length:0;const pct=range?rr/range*100:0;metric=`Tahmini tekrar edilebilirlik payı %${pct.toFixed(1)}`;if(pct>Number(a.fields.acceptance||10))warning="Ölçüm sistemi kabul sınırını aşıyor."}
  if(a.tool==="DOE"){const rows=a.rows.map(r=>({a:n(r.factorA),b:n(r.factorB),y:n(r.response)})).filter(r=>[r.a,r.b,r.y].every(Number.isFinite));const effect=(key:"a"|"b")=>{const hi=rows.filter(r=>r[key]>0),lo=rows.filter(r=>r[key]<0);return hi.length&&lo.length?hi.reduce((s,r)=>s+r.y,0)/hi.length-lo.reduce((s,r)=>s+r.y,0)/lo.length:0};metric=`Ana etkiler: A=${effect("a").toFixed(2)}, B=${effect("b").toFixed(2)}`}
  if(a.tool==="FAULT_TREE"){const ps=a.rows.map(r=>n(r.probability)).filter(x=>Number.isFinite(x)&&x>=0&&x<=1);const gate=a.rows[0]?.gate?.toUpperCase();const p=gate==="AND"?ps.reduce((s,x)=>s*x,1):1-ps.reduce((s,x)=>s*(1-x),1);metric=`Tepe olay tahmini: ${(p*100).toFixed(3)}%`}
  if(a.tool==="BOWTIE"){const weak=a.rows.filter(r=>r.status!=="EFFECTIVE").length;metric=`${a.rows.length-weak}/${a.rows.length} bariyer etkili`;if(weak)warning=`${weak} zayıf veya eksik bariyer var.`}
  if(a.tool==="RCM"){const risks=a.rows.map(r=>n(r.severity)*n(r.occurrence)*n(r.detectability)).filter(Number.isFinite);const max=risks.length?Math.max(...risks):0;metric=`En yüksek bakım risk puanı: ${max}`;if(max>=200)warning="Kritik arıza modu için görev/periyot doğrulaması gerekli."}
  if(a.tool==="TRIZ")metric=`${a.rows.filter(r=>r.principle?.trim()&&r.concept?.trim()).length} çözüm kavramı`;
  if(a.tool==="TOYOTA_KATA")metric=`${a.rows.filter(r=>r.actual?.trim()&&r.learned?.trim()).length}/${a.rows.length} deneyden öğrenme kapandı`;
  if(a.tool==="CAUSAL_LOOP"){const delayed=a.rows.filter(r=>r.delay?.trim()).length;metric=`${a.rows.length} nedensel bağ · ${delayed} gecikmeli bağ`}
  return {ready:missing.length===0&&a.rows.length>0,missing,metric,warning};
}
