export interface BenchmarkReference { id:string; name:string; type:"INTERNAL"|"COMPETITOR"|"FUNCTIONAL"|"GENERIC"; capability:string; localValue:number; referenceValue:number; localScale:number; referenceScale:number; practiceGap:string; adaptation:string; blindCopyRisk:string; evidenceIds:string[] }
export interface CapacityScenario { id:string; name:string; demand:number; availableMinutes:number; bottleneckCycleSeconds:number; yieldRate:number; mixFactor:number; channelMargin:number; shelfLifeDays:number|null; inventory:number; investment:number }
export interface SopScenario { id:string; name:string; strategy:"CHASE"|"LEVEL"|"HYBRID"; demandLow:number; demandExpected:number; demandHigh:number; regularCapacity:number; overtimeCapacity:number; subcontractCapacity:number; openingInventory:number; serviceTarget:number; unitRegularCost:number; unitOvertimeCost:number; unitSubcontractCost:number; unitInventoryCost:number; unitBacklogCost:number }
export interface LineOperation { id:string; name:string; seconds:number; station:number; skill:string; ergonomicRisk:"LOW"|"MEDIUM"|"HIGH"; monotonyRisk:"LOW"|"MEDIUM"|"HIGH"; qualityOwnership:string }
export interface LineBalanceStudy { demand:number; availableSeconds:number; operations:LineOperation[]; mode:"LINE"|"CELL"|"COMPLETE_ASSEMBLY" }

const round=(n:number)=>Math.round(n*100)/100;
export function normalizeBenchmark(item:BenchmarkReference) { const local=item.localScale>0?item.localValue/item.localScale:0; const reference=item.referenceScale>0?item.referenceValue/item.referenceScale:0; return {local:round(local),reference:round(reference),gap:round(reference-local),comparable:item.localScale>0&&item.referenceScale>0&&Boolean(item.capability.trim()&&item.adaptation.trim())}; }
export function calculateCapacity(x:CapacityScenario) { const theoretical=x.bottleneckCycleSeconds>0?x.availableMinutes*60/x.bottleneckCycleSeconds:0; const throughput=theoretical*Math.max(0,Math.min(1,x.yieldRate/100))*Math.max(0,x.mixFactor); const gap=throughput+x.inventory-x.demand; return {throughput:round(throughput),gap:round(gap),utilization:throughput>0?round(x.demand/throughput*100):0,contribution:round(Math.min(throughput,x.demand)*x.channelMargin-x.investment),feasible:gap>=0}; }
export function calculateSop(x:SopScenario) { const supply=x.regularCapacity+x.overtimeCapacity+x.subcontractCapacity+x.openingInventory; const served=Math.min(supply,x.demandExpected); const backlog=Math.max(0,x.demandExpected-supply); const endingInventory=Math.max(0,supply-x.demandExpected); const service=x.demandExpected>0?served/x.demandExpected*100:100; const cost=x.regularCapacity*x.unitRegularCost+x.overtimeCapacity*x.unitOvertimeCost+x.subcontractCapacity*x.unitSubcontractCost+endingInventory*x.unitInventoryCost+backlog*x.unitBacklogCost; return {supply:round(supply),backlog:round(backlog),endingInventory:round(endingInventory),service:round(service),cost:round(cost),meetsTarget:service>=x.serviceTarget&&supply>=x.demandHigh}; }
export function calculateLineBalance(study:LineBalanceStudy) { const takt=study.demand>0?study.availableSeconds/study.demand:0; const stations=new Map<number,number>(); for(const op of study.operations)stations.set(op.station,(stations.get(op.station)??0)+op.seconds); const stationLoads=[...stations.values()]; const bottleneck=stationLoads.length?Math.max(...stationLoads):0; const total=study.operations.reduce((s,x)=>s+x.seconds,0); const efficiency=stations.size&&takt>0?total/(stations.size*takt)*100:0; return {takt:round(takt),stations:stations.size,bottleneck:round(bottleneck),efficiency:round(efficiency),balanceLoss:round(Math.max(0,100-efficiency)),capacity:bottleneck>0?Math.floor(study.availableSeconds/bottleneck):0,overloaded:[...stations.entries()].filter(([,load])=>takt>0&&load>takt).map(([station])=>station),ergonomicHigh:study.operations.filter(x=>x.ergonomicRisk==="HIGH").length}; }
