export interface ContextContract { purpose:string; scope:string; outOfScope:string; successMetric:string; methodRole:string; pivotCondition:string; misuseRisk:string; undesiredBehavior:string; owner:string; approvedBy:string }
export interface SystemBehaviorAnalysis { id:string; observedBehavior:string; systemCondition:string; managementAssumption:string; localKpi:string; incentiveConflict:string; delayedEffect:string; feedbackLoop:string; interventionHypothesis:string; evidenceIds:string[] }
export type QmsDimension = "QUALITY_CAPACITY"|"PRODUCTION_PRESSURE"|"STANDARD_COVERAGE"|"DATA_RELIABILITY"|"COST_OF_QUALITY"|"RECURRENCE"|"CAPA_LOAD"|"PRIORITY_ALIGNMENT";
export interface QmsHealthItem { dimension:QmsDimension; score:1|2|3|4|5; observation:string; evidenceIds:string[]; owner:string; action:string }
export interface GembaBehaviorItem { id:string; processStep:string; expectedStandard:string; actualBehavior:string; humanDecisionPoint:string; repeatedQuestion:string; searchOrMotion:string; errorOpportunity:string; compensationBehavior:string; physicalConstraint:string; pokaYokeIdea:string; evidenceIds:string[] }

export function contextCompleteness(contract:ContextContract) { const required=(Object.keys(contract) as (keyof ContextContract)[]); const complete=required.filter(k=>contract[k].trim()).length; return {complete,total:required.length,ready:complete===required.length}; }
export function isPersonBlaming(statement:string) { return /operatör hatası|insan hatası|dikkatsiz|özensiz|disiplinsiz|eğitimsiz/i.test(statement) && !/sistem|standart|koşul|tasarım|neden izin/i.test(statement); }
export function qmsHealthScore(items:QmsHealthItem[]) { if(!items.length)return {score:0,level:"UNKNOWN" as const,critical:[] as QmsDimension[]}; const score=items.reduce((s,x)=>s+x.score,0)/items.length; return {score,level:score<2.5?"CRITICAL" as const:score<3.5?"FRAGILE" as const:"HEALTHY" as const,critical:items.filter(x=>x.score<=2).map(x=>x.dimension)}; }
export function gembaOpportunityCount(items:GembaBehaviorItem[]) { return items.filter(x=>(x.errorOpportunity??"").trim()||(x.compensationBehavior??"").trim()||(x.pokaYokeIdea??"").trim()).length; }
