import {test,expect} from "@playwright/test";
import {mkdir,readFile,writeFile} from "node:fs/promises";
import path from "node:path";

const output=path.resolve("dokumantasyon");
const shots=path.join(output,"ekran-goruntuleri");
const chapters=[
  {slug:"01-ana-ekran",url:"/",title:"Ana ekran",purpose:"Sistemin değer önerisini, temel çalışma modelini ve teşhise giriş noktasını sunar.",why:"Kullanıcının doğrudan bir metodoloji seçmesi yerine önce problemi tarif etmesini teşvik eder.",input:"Bu ekranda veri girilmez. Yeni analiz için ‘Teşhise başla’ kullanılır.",check:"Doğru kullanıcı yolu problemden başlar; yöntem tercihi teşhis sonucunda yapılır."},
  {slug:"02-teshis",url:"/diagnoz",title:"Problem teşhisi",purpose:"Problem ifadesini bağlama dönüştürür ve soru havuzundan kanıt ayırıcı sorular üretir.",why:"Bir veya iki yüzeysel cevabın yöntemi kesinleştirmesini önler; çoklu sinyal yakınlığı aranır.",input:"Belirtiyi, etkilenen proses/ürünü, başlangıç zamanını, kapsamı ve iş etkisini somut yazın. ‘Kalite kötü’ yerine ölçülebilir sapma belirtin.",check:"Cevaplar gözlem ile yorumu ayırmalı; bilinmeyen konularda tahmin yerine ‘bilinmiyor’ kullanılmalıdır."},
  {slug:"03-genel-bakis",tab:"overview",title:"Çalışma genel bakışı",purpose:"Çalışmanın ilerlemesini, kanıt açığını, açık aksiyonları ve kapanış riskini tek bakışta gösterir.",why:"Formların dolu görünmesi ile problemin gerçekten çözülmesi aynı şey değildir; bu ekran doğrulama borcunu görünür kılar.",input:"Kartlar diğer sekmelerdeki kayıtlardan otomatik oluşur. Riskli karta tıklayarak ilgili alana ilerleyin.",check:"Kapanıştan önce kanıtsız iddia, sahipsiz aksiyon ve bekleyen onay kalmamalıdır."},
  {slug:"04-metodoloji",tab:"methodology",title:"Metodoloji uygulama alanı",purpose:"Seçilen yöntemin adımlarını yapılandırılmış saha çalışmasına dönüştürür.",why:"8D, FMEA, RCA veya A3 adlarının yalnızca etiket olarak kullanılmasını önler; yöntemin beklediği düşünme disiplinini uygular.",input:"Her adımda olgu, ölçüm, kapsam ve karar girdilerini yazın. AI taslağını başlangıç noktası kabul edin; saha doğrulaması olmadan sonuç saymayın.",check:"Bir adımı yalnızca beklenen çıktı oluştuğunda tamamlayın. Sonraki adım önceki adımın kanıtına dayanmalıdır."},
  {slug:"05-proaktif-operasyon",tab:"operations",title:"Proaktif Operasyon — Zayıf Sinyal Merkezi",purpose:"Henüz büyük arızaya dönüşmemiş sapmaları, telafileri ve insan gözlemlerini erken uyarı kaydı olarak yönetir.",why:"Büyük problemler çoğu zaman mikro duruş, tekrar ölçüm, geçici müdahale, fazla mesai veya bakım ertelemesi biçiminde öncü iz bırakır. Bu alan geçmiş hata listesinden farklı olarak gelecekte başarısızlık oluşturabilecek koşulları görünür yapar.",input:"Sinyal türü, tarafsız gözlem, kaynak/istasyon, araştırma hipotezi, doğrulama görevi ve sorumlu girilir. Hipotez kök neden değildir. Örnek: ‘Pres 4 yağ sıcaklığı son üç vardiyada normalin 8°C üzerinde’; kötü örnek: ‘Bakım görevini yapmıyor’.",check:"NEW → TRIAGED → VERIFYING/WATCHING akışını kullanın. Sinyal doğrulanır ve iş etkisi taşıyorsa problem vakasına yükseltin; kanıt yoksa gerekçeli biçimde kapatın."},
  {slug:"06-organizasyon",tab:"organization",title:"Organizasyon ve Bağlam",purpose:"Teknik problem ile sistem davranışı, QMS sağlığı, gemba davranışı ve çalışma bağlamı arasındaki ilişkiyi inceler.",why:"İnsan hatası etiketi; hedef çelişkisi, eğitim açığı, standart dışı iş veya yönetim sistemi zafiyetini saklayabilir.",input:"Amaç, kapsam, kapsam dışı alan, başarı metriği, sahip ve pivot koşulunu yazın. Kişi suçlayan ifadeleri süreç koşullarına çevirin.",check:"Analiz kişiyi değil davranışı üreten koşulları açıklamalı; QMS aksiyonlarının sahibi belli olmalıdır."},
  {slug:"07-karar-laboratuvarlari",tab:"labs",title:"Karar Laboratuvarları",purpose:"Kapasite, S&OP, hat dengeleme ve benchmark kararlarını hesaplanabilir senaryolara dönüştürür.",why:"Kapasite ve yatırım kararlarının sezgiyle değil varsayım, kısıt ve sonuç görünürlüğüyle verilmesini sağlar.",input:"Talep, çevrim süresi, kullanılabilir süre, verim, stok ve servis hedeflerini aynı birimlerle girin. Benchmark kaynağını ve bağlam farkını kaydedin.",check:"Birimleri doğrulayın; imkânsız senaryoyu gizlemeyin. Sonuç karar değildir, kararın kanıt girdisidir."},
  {slug:"08-ileri-analiz",tab:"advanced",title:"İleri Analizler",purpose:"Standart metodolojinin yetmediği durumlarda sistem haritalama, senaryo ve uzman analizlerini kanıt bağlantısıyla yürütür.",why:"Her probleme ağır araç uygulamak yerine yalnızca karar noktasında ek çözünürlük gerektiğinde kullanılır.",input:"Araç, karar noktası, hipotez, analiz satırları, sonuç ve destekleyen kanıtları girin.",check:"Analiz ‘tamamlandı’ olmadan önce sonuç ve kanıt bağlantısı bulunmalıdır."},
  {slug:"09-kanit-kapanis",tab:"validation",title:"Kanıt ve Kapanış",purpose:"Uzman kalibrasyonu, containment, iddia–kanıt ilişkisi, red-team sorgusu ve etkinlik doğrulamasını bir araya getirir.",why:"Bir aksiyonun uygulanması onun etkili olduğunu; bir iddianın tekrarlanması da doğru olduğunu göstermez.",input:"Önerilen/seçilen yöntem ayrımını, karar gerekçesini ve gerçek saha sonucunu kaydedin. Kanıta kaynak, bulgu ve tarih; iddiaya ilgili kanıt kimliklerini bağlayın.",check:"Kök neden kanıtlanmalı, karşı-olgusal sorgu cevaplanmalı, geçici kontrol kaldırma kriteri karşılanmalı ve izleme başarılı olmalıdır."},
  {slug:"10-aksiyonlar",tab:"actions",title:"Aksiyonlar",purpose:"Probleme karşı alınan önlemleri sahip, termin, hedef neden ve etkinlik ölçütüyle yönetir.",why:"‘Eğitim verildi’ gibi takip edilemeyen niyetleri doğrulanabilir taahhütlere dönüştürür.",input:"Fiil ile başlayan somut aksiyon, tek sorumlu, gerçekçi termin, hedef kök neden, başlangıç/amaç/gerçek değer ve kanıt bağlantısı girin.",check:"IMPLEMENTED yalnızca uygulamayı; EFFECTIVE kanıtlanmış etkiyi belirtir. Etkisiz aksiyon kapanmış sayılmaz."},
  {slug:"11-yayilim",tab:"deployment",title:"Yayılım ve bağlı çalışmalar",purpose:"Aynı riskin diğer hat, ürün, tesis ve proseslerde bulunup bulunmadığını kontrol eder.",why:"Yerel düzeltmenin kurumsal tekrar riskini azaltması için yokoten ve takip çalışmaları gerekir.",input:"Hedef alanı, risk düzeyini, tarama sonucunu, sahibi ve gerekirse açılan bağlı çalışma kimliğini girin.",check:"Risk bulunan hedef, aksiyonsuz veya bağlı çalışma olmadan tamamlanmamalıdır."},
  {slug:"12-ogrenim",tab:"learning",title:"Öğrenim ve sistem dokümanları",purpose:"Çözümü standart işe, kontrol planına, FMEA’ya, bakım planına veya OPL’ye dönüştürür.",why:"Yalnızca vaka raporunda kalan bilgi personel değişiminde kaybolur ve problem tekrarlanır.",input:"Öğrenim özeti, değişecek doküman, revizyon, sahip, onaylayan, yürürlük tarihi ve değişiklik gerekçesini yazın.",check:"Etkili önlemin hangi sistem dokümanını değiştirdiği açıklanmalı; değişiklik gerekmiyorsa gerekçesi onaylanmalıdır."},
  {slug:"13-rapor",tab:"report",title:"Rapor",purpose:"Çalışmanın problem, analiz, karar, kanıt, aksiyon ve sonuç hikâyesini yönetilebilir çıktıya dönüştürür.",why:"Paydaşların bütün formları okumadan karar mantığını ve kalan riski görmesini sağlar.",input:"Rapor üretmeden önce temel alanları tamamlayın; oluşturulan metni gerçek tarihler, ölçümler ve kararlarla gözden geçirin.",check:"Rapor belirsiz iddiaları kesin gerçek gibi göstermemeli ve açık riskleri saklamamalıdır."},
  {slug:"14-gecmis",tab:"history",title:"Geçmiş",purpose:"Çalışmadaki önemli değişikliklerin ve yaşam döngüsü kararlarının zaman çizgisini gösterir.",why:"Kararın hangi sırayla ve hangi gerekçeyle oluştuğunun geriye dönük anlaşılmasını sağlar.",input:"Kayıtlar sistem işlemlerinden oluşur; kullanıcı açıklamalarında karar gerekçesini anlaşılır yazmalıdır.",check:"Admin paneli için ertelenen aktör bazlı ayrıntılı denetim iziyle karıştırılmamalıdır; mevcut görünüm çalışma olay geçmişidir."},
  {slug:"15-gorev-merkezi",url:"/gorevler",title:"Görev ve Takip Merkezi",purpose:"Farklı çalışmaların aksiyon, containment, sinyal, QMS, OPL ve izleme yükümlülüklerini tek listede toplar.",why:"İşlerin metodoloji sekmelerinde unutulmasını önler ve termin riskini portföy düzeyinde gösterir.",input:"Görevler kaynak kayıtlardan otomatik oluşur. Düzenlemek için satırdan ilgili çalışma sekmesine gidin.",check:"Önce gecikenler, sonra yaklaşan işler ele alınmalı; sahipsiz görev bırakılmamalıdır."},
  {slug:"16-yonetici-panosu",url:"/dashboard",title:"Yönetici Panosu",purpose:"Açık çalışma, doğrulama borcu, zayıf sinyal, geçici kontrol, kapasite açığı ve kalibrasyon sonucunu portföy seviyesinde izler.",why:"Faaliyet sayısından çok karar kalitesi, kanıt ve sürdürülebilir sonuç görünürlüğü sağlar.",input:"Doğrudan veri girilmez; kartlar çalışmalardan hesaplanır.",check:"Yüksek sayı her zaman kötü değildir; trend, yaş, iş etkisi ve kapanış kalitesiyle birlikte yorumlanmalıdır."},
  {slug:"17-aktarim",url:"/aktarim",title:"Veri Aktarımı",purpose:"Sistemden alınmış sürümlü JSON çalışma paketini doğrulayarak yeni çalışma olarak içe aktarır.",why:"Kurulumlar arası taşıma ve kontrollü yedek dönüşü sağlarken mevcut kaydın yanlışlıkla ezilmesini önler.",input:"Yalnızca sistemin JSON dışa aktarma çıktısını yükleyin. CSV dosyası içe aktarma için değil denetim ve toplantı kullanımı içindir.",check:"İçe aktarılan kaydın yöntem, problem tanımı, kanıt ve aksiyonlarını açıp kontrol edin."},
];

test("ayrıntılı frontend kullanım kılavuzu ve PDF üret",async({page,request})=>{
  await mkdir(shots,{recursive:true});
  const created=await request.post("/api/workspace",{data:{methodology:"FMEA",problemDescription:"Pres hattı P4 rulman sıcaklığı ve mikro duruş artışı — Kılavuz örnek vakası"}});
  expect(created.status()).toBe(201);const ws=await created.json();
  const patch=await request.patch(`/api/workspace/${ws.id}`,{data:{
    weakSignals:[{id:"guide_signal_1",type:"PROCESS_MEASUREMENT",description:"Pres 4 ana rulman sıcaklığı son üç vardiyada baz değerin 8°C üzerinde ve mikro duruşlar %22 arttı.",source:"Pres 4 / IoT sıcaklık sensörü ve vardiya duruş kaydı",detectedAt:"2026-07-19",status:"VERIFYING",hypothesis:"Yağlama debisi düşüşü sürtünmeyi artırıyor olabilir; henüz kök neden değildir.",verificationTask:"Yağ debisini ölç, termal kamera trendini ürün değişimleriyle karşılaştır.",owner:"Bakım Mühendisi",dueDate:"2026-07-22",evidenceIds:[],linkedWorkspaceId:null}],
    evidence:[{id:"guide_ev_1",title:"72 saatlik sıcaklık trendi",source:"Pres 4 historian",finding:"Ürün B çalışırken sıcaklık baz değerden ortalama 8°C yüksek.",stepKey:null,claimId:null,recordedAt:"2026-07-19"}],
    claims:[{id:"guide_claim_1",statement:"Yağlama debisi düşüşü sıcaklık artışının olası nedenidir.",kind:"HYPOTHESIS",status:"CLAIMED",stepKey:null,evidenceIds:["guide_ev_1"],counterfactual:"Debi normal olduğunda aynı sıcaklık artışı devam ediyorsa hipotez zayıflar."}],
    actions:[{action:"Pres 4 yağlama debisini kalibre edilmiş ölçüm cihazıyla doğrula",owner:"Bakım Mühendisi",status:"IN_PROGRESS",dueDate:"2026-07-22",targetCauseId:"guide_claim_1",successMetric:"Debi ve sıcaklık korelasyonu",baseline:"Sıcaklık +8°C",target:"Baz değerin en fazla +2°C üzeri",actual:"",verificationDueDate:"2026-07-25",evidenceIds:["guide_ev_1"]}],
    recommendationFeedback:{decision:"ACCEPTED",recommendedMethodology:"FMEA",selectedMethodology:"FMEA",reason:"Koşul değişikliklerini ve henüz gerçekleşmemiş arıza modlarını değerlendirmek gerekiyor.",reviewedAt:"2026-07-19",outcome:"PENDING",outcomeNote:"Pilot uygulama sürüyor.",outcomeAt:null}
  }});expect(patch.ok()).toBeTruthy();

  for(const chapter of chapters){const url=chapter.tab?`/workspace/${ws.id}?tab=${chapter.tab}`:chapter.url!;await page.goto(url);await page.waitForLoadState("networkidle");await page.screenshot({path:path.join(shots,`${chapter.slug}.png`),fullPage:false});}

  const images:Record<string,string>={};for(const chapter of chapters){images[chapter.slug]=(await readFile(path.join(shots,`${chapter.slug}.png`))).toString("base64")}
  const body=chapters.map((chapter,index)=>`<section class="chapter"><div class="number">${String(index+1).padStart(2,"0")}</div><h2>${chapter.title}</h2><img src="data:image/png;base64,${images[chapter.slug]}" alt="${chapter.title} ekran görüntüsü"><h3>Bu ekran nedir?</h3><p>${chapter.purpose}</p><h3>Neden sistemde var?</h3><p>${chapter.why}</p><h3>Ne yazılmalı / nasıl kullanılmalı?</h3><p>${chapter.input}</p><h3>Kontrol noktası</h3><p class="check">${chapter.check}</p></section>`).join("");
  const html=`<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Manufacturing Decision Engine — Frontend Kullanım Kılavuzu</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;line-height:1.55;margin:0}.cover{height:255mm;display:flex;flex-direction:column;justify-content:center;background:linear-gradient(145deg,#eef2ff,#ecfdf5);padding:28mm;border-radius:16px}.cover h1{font-size:34px;line-height:1.15;margin:12px 0}.cover p{font-size:16px;color:#475569}.tag{color:#4f46e5;font-size:12px;font-weight:bold;letter-spacing:1.5px}.chapter{break-before:page}.number{color:#4f46e5;font-weight:bold;margin-top:2mm}.chapter h2{font-size:24px;margin:2mm 0 5mm}.chapter img{width:100%;max-height:112mm;object-fit:contain;object-position:top;border:1px solid #cbd5e1;border-radius:8px;background:#f8fafc}.chapter h3{font-size:14px;color:#334155;margin:5mm 0 1mm}.chapter p{font-size:11.5px;margin:0}.check{background:#ecfdf5;border-left:4px solid #10b981;padding:3mm}.intro{break-before:page}.intro h2{font-size:24px}.intro table{width:100%;border-collapse:collapse;font-size:11px}.intro td,.intro th{border:1px solid #cbd5e1;padding:7px;text-align:left}.footer{font-size:9px;color:#64748b}</style></head><body><section class="cover"><div class="tag">KULLANICI VE EKRAN REHBERİ</div><h1>Manufacturing Decision Engine</h1><p>Frontend ekranlarının amacı, kullanım mantığı, girilmesi gereken bilgiler ve kontrol noktaları</p><p class="footer">Örnek vaka: Pres 4 rulman sıcaklığı ve mikro duruş artışı<br>Oluşturma tarihi: 19 Temmuz 2026</p></section><section class="intro"><h2>Bu doküman nasıl kullanılmalı?</h2><p>Bu kılavuz bir alan sözlüğü değil, karar rehberidir. Her bölüm ekranın ne yaptığını, neden tasarlandığını, kullanıcıdan hangi kalitede bilgi beklediğini ve bir sonraki aşamaya geçmeden önce neyin kontrol edilmesi gerektiğini açıklar.</p><table><tr><th>İlke</th><th>Uygulama</th></tr><tr><td>Olgu ve yorum ayrımı</td><td>Ölçüm/gözlem kanıttır; neden açıklaması doğrulanana kadar hipotezdir.</td></tr><tr><td>Minimum karar kanıtı</td><td>Bir veya iki sinyal kesin yöntem seçimi ya da kök neden ilanı için yeterli değildir.</td></tr><tr><td>Etkinlik ayrımı</td><td>Aksiyonun uygulanması ile problemin kalıcı biçimde azaldığının doğrulanması ayrı durumdur.</td></tr><tr><td>Sistem düşüncesi</td><td>Kişi suçlamak yerine davranışı ve hatayı üreten proses koşulları araştırılır.</td></tr><tr><td>Gelecek odaklı risk</td><td>Geçmiş olayların yanında koşul değiştiğinde oluşabilecek yeni başarısızlıklar incelenir.</td></tr></table></section>${body}</body></html>`;
  await writeFile(path.join(output,"FRONTEND_KULLANIM_KILAVUZU.html"),html,"utf8");
  await page.setContent(html,{waitUntil:"load"});
  await page.pdf({path:path.join(output,"FRONTEND_KULLANIM_KILAVUZU.pdf"),format:"A4",printBackground:true,displayHeaderFooter:true,headerTemplate:"<span></span>",footerTemplate:'<div style="font-size:8px;color:#64748b;width:100%;text-align:center">Manufacturing Decision Engine · Frontend Kullanım Kılavuzu · <span class="pageNumber"></span>/<span class="totalPages"></span></div>',margin:{top:"15mm",right:"15mm",bottom:"18mm",left:"15mm"}});
});
