import Link from "next/link";
import { getWorkspaceService } from "@/application/wiring";
import { FEATURE_KEYS, FEATURE_META, METHODOLOGIES, METHODOLOGY_META, RULES } from "@/domain/diagnosis";
import { DEFAULT_STOP_POLICY } from "@/domain/diagnosis/question-engine";
import { PLAYBOOKS } from "@/domain/playbook";
import { adminPassword, appPassword } from "@/lib/auth";
import { AdminWorkspaceDeleteButton } from "@/components/admin-workspace-delete-button";

export const dynamic = "force-dynamic";
export const metadata = { title:"Admin Paneli · Manufacturing Diagnosis Engine" };

const closureLabel = { OPEN:"Açık", CLOSURE_CANDIDATE:"Kapanış adayı", MONITORING:"İzlemede", CLOSED:"Kapalı", REOPENED:"Yeniden açıldı" } as const;

export default async function AdminPage() {
  const service=getWorkspaceService();
  const [dashboard,workspaces,tasks]=await Promise.all([service.dashboard(),service.list(),service.taskCenter()]);
  const openTasks=tasks.filter((task)=>task.status!=="DONE");
  const overdue=openTasks.filter((task)=>task.status==="OVERDUE").length;
  const ruleEffects=RULES.reduce((sum,rule)=>sum+Object.keys(rule.effect).length,0);
  const playbookSteps=Object.values(PLAYBOOKS).reduce((sum,book)=>sum+book.steps.length,0);
  const playbookFields=Object.values(PLAYBOOKS).reduce((sum,book)=>sum+book.steps.reduce((stepSum,step)=>stepSum+step.fields.length,0),0);

  return <main className="page-shell flex-1">
    <header className="section-toolbar"><div><p className="eyebrow">Sistem yönetimi</p><h1 className="page-heading mt-1">Admin paneli</h1><p className="page-lead">Operasyon portföyünü, teşhis yönetişimini, metodoloji kapsamını ve çalışma ortamının güvenlik durumunu tek noktadan denetleyin.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard" className="btn btn-secondary">Kullanıcı panosuna dön</Link><form action="/api/admin/logout" method="post"><button className="btn btn-ghost">Admin oturumunu kapat</button></form></div></header>

    <nav className="scroll-fade sticky top-16 z-20 mt-6 flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white/95 p-2 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-950/95" aria-label="Admin bölümleri">
      {[['overview','Genel bakış'],['portfolio','Çalışmalar'],['diagnosis','Teşhis yönetişimi'],['playbooks','Metodoloji kapsamı'],['system','Sistem ve erişim']].map(([id,label])=><a key={id} className="workspace-tab" href={`#${id}`}>{label}</a>)}
    </nav>

    <section id="overview" className="scroll-mt-32 mt-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
      <AdminMetric label="Toplam çalışma" value={dashboard.total} detail={`${dashboard.open} açık`} tone="indigo"/>
      <AdminMetric label="Geciken görev" value={overdue} detail={`${openTasks.length} açık görev`} tone={overdue?"red":"green"}/>
      <AdminMetric label="Kanıtsız iddia" value={dashboard.unverifiedClaims} detail="Doğrulama borcu" tone={dashboard.unverifiedClaims?"amber":"green"}/>
      <AdminMetric label="Etkinlik bekleyen" value={dashboard.effectivenessDue} detail="Aksiyon sonucu" tone={dashboard.effectivenessDue?"amber":"green"}/>
      <AdminMetric label="Zayıf sinyal" value={dashboard.weakSignalsOpen} detail="Açık erken uyarı" tone={dashboard.weakSignalsOpen?"amber":"green"}/>
      <AdminMetric label="Yeniden açılan" value={dashboard.reopened} detail="İzleme başarısızlığı" tone={dashboard.reopened?"red":"green"}/>
      <AdminMetric label="Saha pilotu" value={dashboard.pilotsRunning} detail={`${dashboard.pilotsCompleted} tamamlandı`} tone={dashboard.pilotsRunning?"indigo":"amber"}/>
      <AdminMetric label="Sahada doğrulanan" value={dashboard.fieldValidated} detail="Gerçek sonuç kayıtlı" tone={dashboard.fieldValidated?"green":"amber"}/>
      <AdminMetric label="Entegrasyon" value={dashboard.integrationLinks} detail={`${dashboard.integrationErrors} hata`} tone={dashboard.integrationErrors?"red":"indigo"}/>
      <AdminMetric label="Kalite engeli" value={dashboard.blockingQualityFindings} detail="Kapanışı durduran" tone={dashboard.blockingQualityFindings?"red":"green"}/>
    </div></section>

    <section className="card mt-6 p-5" aria-labelledby="workspace-cleanup-heading">
      <div className="section-toolbar"><div><p className="eyebrow">Portföy yönetimi</p><h2 id="workspace-cleanup-heading" className="section-heading mt-1">Deneme çalışmalarını kaldır</h2><p className="mt-1 text-xs text-slate-400">Gerçek kullanıma geçmeden önce gereksiz kayıtları ve bunlara yüklenen kanıt dosyalarını kalıcı olarak temizleyin.</p></div><span className="status-badge bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-300">Geri alınamaz</span></div>
      <div className="mt-4 divide-y divide-slate-200 rounded-xl border border-slate-200 dark:divide-slate-800 dark:border-slate-800">{workspaces.slice(0,30).map((workspace)=><div key={workspace.id} className="flex flex-col gap-3 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><strong className="block truncate text-sm">{workspace.problemDescription}</strong><small className="text-slate-400">{workspace.methodologyName} · {new Date(workspace.updatedAt).toLocaleString('tr-TR')}</small></div><AdminWorkspaceDeleteButton id={workspace.id} name={workspace.problemDescription}/></div>)}{!workspaces.length&&<p className="p-6 text-center text-sm text-slate-400">Kaldırılabilecek çalışma bulunmuyor.</p>}</div>
    </section>

    <section id="portfolio" className="card scroll-mt-32 mt-6 overflow-hidden"><div className="section-toolbar border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div><p className="eyebrow">Portföy yönetimi</p><h2 className="section-heading mt-1">Son güncellenen çalışmalar</h2><p className="mt-1 text-xs text-slate-400">Durum, metodoloji, ilerleme ve açık güvence borcunu birlikte gösterir.</p></div><Link href="/gorevler" className="btn btn-secondary">Tüm görevleri aç</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500 dark:bg-slate-900/70"><tr><th className="px-5 py-3">Çalışma</th><th className="px-3 py-3">Metodoloji</th><th className="px-3 py-3">Yaşam döngüsü</th><th className="px-3 py-3">İlerleme</th><th className="px-3 py-3">Açıklar</th><th className="px-5 py-3 text-right">İşlem</th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-slate-800">{workspaces.slice(0,30).map((workspace)=><tr key={workspace.id} className="hover:bg-indigo-50/30 dark:hover:bg-indigo-950/20"><td className="max-w-md px-5 py-3"><strong className="block truncate">{workspace.problemDescription}</strong><small className="text-slate-400">{new Date(workspace.updatedAt).toLocaleString('tr-TR')}</small></td><td className="px-3 py-3">{workspace.methodologyName}</td><td className="px-3 py-3"><span className="status-badge bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{closureLabel[workspace.closureStatus]}</span></td><td className="px-3 py-3 tabular-nums">{workspace.doneSteps}/{workspace.totalSteps}</td><td className="px-3 py-3 text-xs text-slate-500">{workspace.openActions} aksiyon · {workspace.unverifiedClaims} iddia</td><td className="px-5 py-3 text-right"><Link className="font-semibold text-indigo-600 hover:underline" href={`/workspace/${workspace.id}`}>İncele →</Link></td></tr>)}{!workspaces.length&&<tr><td colSpan={6} className="p-10 text-center text-slate-400">Henüz çalışma bulunmuyor.</td></tr>}</tbody></table></div>{workspaces.length>30&&<p className="border-t border-slate-200 px-5 py-3 text-xs text-slate-400 dark:border-slate-800">İlk 30 kayıt gösteriliyor. Tam liste için Çalışmalar ekranını kullanın.</p>}</section>

    <section id="diagnosis" className="scroll-mt-32 mt-6 grid gap-5 xl:grid-cols-2"><div className="card p-5"><p className="eyebrow">Soru kataloğu</p><h2 className="section-heading mt-1">{FEATURE_KEYS.length} teşhis değişkeni</h2><p className="mt-1 text-xs text-slate-400">Sorular sürümlü kaynak kodundan gelir; burada hangi karar sinyalinin kullanıcıya nasıl sorulduğunu denetleyin.</p><div className="mt-4 max-h-[620px] space-y-2 overflow-y-auto pr-1">{FEATURE_KEYS.map((key)=><details key={key} className="subtle-panel py-3"><summary className="cursor-pointer text-sm font-semibold">{FEATURE_META[key].label}<span className="ml-2 font-mono text-[10px] font-normal text-slate-400">{key}</span></summary><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{FEATURE_META[key].questionTheme}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><span className="rounded-lg bg-emerald-50 p-2 text-[11px] text-emerald-700 dark:bg-emerald-950/30">Evet: {FEATURE_META[key].traceWhenTrue}</span><span className="rounded-lg bg-slate-100 p-2 text-[11px] text-slate-600 dark:bg-slate-800">Hayır: {FEATURE_META[key].traceWhenFalse}</span></div></details>)}</div></div>
      <div className="card p-5"><p className="eyebrow">Kural yönetişimi</p><h2 className="section-heading mt-1">{RULES.length} kural · {ruleEffects} metodoloji etkisi</h2><p className="mt-1 text-xs text-slate-400">Canlı ağırlıklar yalnız testli kaynak sürümüyle değiştirilir. Bu ekran karar motorunun okunabilir envanteridir.</p><div className="mt-4 max-h-[620px] space-y-2 overflow-y-auto pr-1">{RULES.map((rule)=><details key={rule.id} className="subtle-panel py-3"><summary className="cursor-pointer text-sm font-semibold"><span className="mr-2 font-mono text-xs text-indigo-600">{rule.id}</span>{rule.because}</summary><p className="mt-2 text-[11px] text-slate-500">Okunan sinyaller: {rule.reads.map((key)=>FEATURE_META[key].label).join(', ')}</p><div className="mt-2 flex flex-wrap gap-1.5">{Object.entries(rule.effect).map(([methodology,score])=><span key={methodology} className={`rounded-full px-2 py-1 text-[10px] font-semibold ${(score??0)>0?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{METHODOLOGY_META[methodology as keyof typeof METHODOLOGY_META].shortName} {Number(score)>0?'+':''}{score}</span>)}</div></details>)}</div></div>
      <div className="card p-5 xl:col-span-2"><p className="eyebrow">Sonuçlandırma politikası</p><h2 className="section-heading mt-1">Erken ve zayıf öneriyi engelleyen eşikler</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(DEFAULT_STOP_POLICY).map(([key,value])=><div key={key} className="subtle-panel"><p className="font-mono text-[10px] text-slate-400">{key}</p><strong className="mt-1 block text-xl">{value}</strong></div>)}</div></div>
    </section>

    <section id="playbooks" className="card scroll-mt-32 mt-6 p-5"><div className="section-toolbar"><div><p className="eyebrow">Metodoloji kapsamı</p><h2 className="section-heading mt-1">{METHODOLOGIES.length} yöntem · {playbookSteps} adım · {playbookFields} yapılandırılmış alan</h2><p className="mt-1 text-xs text-slate-400">Her uygulama alanının sunduğu profesyonel yürütme şablonu.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{METHODOLOGIES.map((methodology)=>{const book=PLAYBOOKS[methodology];const fields=book.steps.reduce((sum,step)=>sum+step.fields.length,0);return <Link href={`/diagnoz`} key={methodology} className="card card-interactive p-4"><div className="flex items-center justify-between gap-2"><strong>{METHODOLOGY_META[methodology].shortName}</strong><span className="text-xs text-slate-400">{book.steps.length} adım · {fields} alan</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{book.intro}</p></Link>})}</div></section>

    <section id="system" className="scroll-mt-32 mt-6 grid gap-5 lg:grid-cols-2"><div className="card p-5"><p className="eyebrow">Çalışma ortamı</p><h2 className="section-heading mt-1">Yapılandırma sağlığı</h2><div className="mt-4 space-y-3"><ConfigRow label="Uygulama erişimi" ready={Boolean(appPassword())} readyText="APP_PASSWORD tanımlı" missingText="Parolasız yerel mod"/><ConfigRow label="Ayrı admin erişimi" ready={Boolean(adminPassword())} readyText="ADMIN_PASSWORD ile ayrıştırıldı" missingText="Uygulama oturumu yönetici kabul ediliyor"/><ConfigRow label="Kalıcı veri tabanı" ready={process.env.PERSISTENCE==='prisma'} readyText="PostgreSQL / Prisma" missingText="Bellek modu; yeniden başlatmada veri kaybolabilir"/><ConfigRow label="AI sağlayıcısı" ready={Boolean(process.env.AI_PROVIDER&&process.env.AI_PROVIDER!=='none')} readyText={process.env.AI_PROVIDER??'Etkin'} missingText="Deterministik mod"/></div></div><div className="card p-5"><p className="eyebrow">Erişim modeli</p><h2 className="section-heading mt-1">Tek kiracılı yönetim</h2><p className="mt-2 text-sm leading-6 text-slate-500">Bu sürüm kullanıcı hesapları yerine uygulama ve admin oturumlarını ayırır. Kişi bazlı rol, kullanıcı daveti ve aktör bazlı ayrıntılı denetim için ilişkisel kullanıcı modeli gerekir.</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50/60 p-4 text-xs leading-5 text-amber-800 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200"><strong>Üretim önerisi:</strong> `APP_PASSWORD` ve farklı bir `ADMIN_PASSWORD` tanımlayın; HTTPS kullanın. Çok kullanıcılı kurulumdan önce kullanıcı/rol modelini etkinleştirin.</div></div></section>
  </main>;
}

function AdminMetric({label,value,detail,tone}:{label:string;value:number;detail:string;tone:'indigo'|'red'|'amber'|'green'}) { const colors={indigo:'rgba(99,102,241,.15)',red:'rgba(244,63,94,.15)',amber:'rgba(245,158,11,.16)',green:'rgba(16,185,129,.15)'};return <div className="card stat-card" style={{'--stat-color':colors[tone]} as React.CSSProperties}><p className="text-xs font-medium text-slate-500">{label}</p><strong className="mt-1 block text-3xl tracking-tight">{value}</strong><p className="mt-1 text-[11px] text-slate-400">{detail}</p></div> }
function ConfigRow({label,ready,readyText,missingText}:{label:string;ready:boolean;readyText:string;missingText:string}) { return <div className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-3 dark:border-slate-800"><div><strong className="block text-sm">{label}</strong><span className="text-xs text-slate-400">{ready?readyText:missingText}</span></div><span className={`status-badge ${ready?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40':'bg-amber-50 text-amber-700 dark:bg-amber-950/40'}`}>{ready?'Hazır':'Dikkat'}</span></div> }
