import Link from "next/link";
import { getWorkspaceService } from "@/application/wiring";
import { FEATURE_KEYS, FEATURE_META, METHODOLOGIES, METHODOLOGY_META, RULES } from "@/domain/diagnosis";
import { DEFAULT_STOP_POLICY } from "@/domain/diagnosis/question-engine";
import { PLAYBOOKS } from "@/domain/playbook";
import { adminPassword } from "@/lib/auth";
import { AdminWorkspaceDeleteButton } from "@/components/admin-workspace-delete-button";
import { Readout } from "@/components/readout";
import { prisma } from "@/lib/prisma";
import { accountAuthEnabled } from "@/lib/account-auth";
import { parserFallbackMetrics } from "@/infrastructure/parser/resilient-problem-parser";

export const dynamic = "force-dynamic";
export const metadata = { title:"Admin Paneli · Manufacturing Diagnosis Engine" };

const closureLabel = { OPEN:"Açık", CLOSURE_CANDIDATE:"Kapanış adayı", MONITORING:"İzlemede", CLOSED:"Kapalı", REOPENED:"Yeniden açıldı" } as const;

export default async function AdminPage() {
  const service=getWorkspaceService();
  const [dashboard,workspaces,tasks,userCount,organizationCount]=await Promise.all([service.dashboard(),service.list(),service.taskCenter(),prisma.user.count().catch(()=>0),prisma.organization.count().catch(()=>0)]);
  const openTasks=tasks.filter((task)=>task.status!=="DONE");
  const overdue=openTasks.filter((task)=>task.status==="OVERDUE").length;
  const ruleEffects=RULES.reduce((sum,rule)=>sum+Object.keys(rule.effect).length,0);
  const playbookSteps=Object.values(PLAYBOOKS).reduce((sum,book)=>sum+book.steps.length,0);
  const playbookFields=Object.values(PLAYBOOKS).reduce((sum,book)=>sum+book.steps.reduce((stepSum,step)=>stepSum+step.fields.length,0),0);
  const parserFallbacks=parserFallbackMetrics();

  return <main className="page-shell flex-1">
    <header className="section-toolbar"><div><p className="eyebrow">Sistem yönetimi</p><h1 className="page-heading mt-1">Admin paneli</h1><p className="page-lead">Operasyon portföyünü, teşhis yönetişimini, metodoloji kapsamını ve çalışma ortamının güvenlik durumunu tek noktadan denetleyin.</p></div><div className="flex flex-wrap gap-2"><Link href="/dashboard" className="btn btn-secondary">Kullanıcı panosuna dön</Link><form action="/api/admin/logout" method="post"><button className="btn btn-ghost">Admin oturumunu kapat</button></form></div></header>

    <nav className="scroll-fade sticky top-14 z-20 mt-6 flex gap-1 overflow-x-auto border border-[var(--rule-strong)] bg-[var(--surface)] p-2" aria-label="Admin bölümleri">
      {[['overview','Genel bakış'],['portfolio','Çalışmalar'],['diagnosis','Teşhis yönetişimi'],['playbooks','Metodoloji kapsamı'],['system','Sistem ve erişim']].map(([id,label])=><a key={id} className="workspace-tab" href={`#${id}`}>{label}</a>)}
    </nav>

    <section id="overview" className="scroll-mt-32 mt-6"><div className="grid gap-px border-y border-[var(--rule-strong)] bg-[var(--rule)] sm:grid-cols-2 xl:grid-cols-6">
      <AdminMetric label="Kullanıcı hesabı" value={userCount} detail={`${organizationCount} şirket hesabı`} tone="indigo"/>
      <AdminMetric label="Toplam çalışma" value={dashboard.total} detail={`${dashboard.open} açık`} tone="indigo"/>
      <AdminMetric label="Geciken görev" value={overdue} detail={`${openTasks.length} açık görev`} tone={overdue?"red":"green"}/>
      <AdminMetric label="Kanıtsız iddia" value={dashboard.unverifiedClaims} detail="Doğrulama borcu" tone={dashboard.unverifiedClaims?"amber":"green"}/>
      <AdminMetric label="Etkinlik bekleyen" value={dashboard.effectivenessDue} detail="Aksiyon sonucu" tone={dashboard.effectivenessDue?"amber":"green"}/>
      <AdminMetric label="Zayıf sinyal" value={dashboard.weakSignalsOpen} detail="Açık erken uyarı" tone={dashboard.weakSignalsOpen?"amber":"green"}/>
      <AdminMetric label="Yeniden açılan" value={dashboard.reopened} detail="İzleme başarısızlığı" tone={dashboard.reopened?"red":"green"}/>
      <AdminMetric label="Saha pilotu" value={dashboard.pilotsRunning} detail={`${dashboard.pilotsCompleted} tamamlandı`} tone={dashboard.pilotsRunning?"indigo":"amber"}/>
      <AdminMetric label="Sahada doğrulanan" value={dashboard.fieldValidated} detail="Gerçek sonuç kayıtlı" tone={dashboard.fieldValidated?"green":"amber"}/>
      <AdminMetric label="Entegrasyon" value={dashboard.integrationLinks} detail={`${dashboard.integrationErrors} hata`} tone={dashboard.integrationErrors?"red":"indigo"}/>
      <AdminMetric label="Kalite engeli" value={dashboard.blockingQualityFindings} detail="Kapanışı durduran" tone={dashboard.blockingQualityFindings?"red":"green"}/>
      <AdminMetric label="Parser yedeği" value={parserFallbacks.initialFallbacks+parserFallbacks.answerFallbacks} detail={parserFallbacks.lastFallbackAt?`Bu sunucu örneğinde son: ${new Date(parserFallbacks.lastFallbackAt).toLocaleString('tr-TR')}`:"Bu sunucu örneğinde fallback yok"} tone={parserFallbacks.initialFallbacks+parserFallbacks.answerFallbacks?"amber":"green"}/>
    </div></section>

    <section className="card mt-6 p-5" aria-labelledby="workspace-cleanup-heading">
      <div className="section-toolbar"><div><p className="eyebrow">Portföy yönetimi</p><h2 id="workspace-cleanup-heading" className="section-heading mt-1">Deneme çalışmalarını kaldır</h2><p className="mt-1 text-xs text-[var(--muted-2)]">Gerçek kullanıma geçmeden önce gereksiz kayıtları ve bunlara yüklenen kanıt dosyalarını kalıcı olarak temizleyin.</p></div><span className="tag state-risk">Geri alınamaz</span></div>
      <div className="record-list mt-4">{workspaces.slice(0,30).map((workspace)=><div key={workspace.id} className="record-row flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><strong className="block truncate text-sm">{workspace.problemDescription}</strong><small className="text-[var(--muted-2)]">{workspace.methodologyName} · {new Date(workspace.updatedAt).toLocaleString('tr-TR')}</small></div><AdminWorkspaceDeleteButton id={workspace.id} name={workspace.problemDescription}/></div>)}{!workspaces.length&&<p className="p-6 text-center text-sm text-[var(--muted-2)]">Kaldırılabilecek çalışma bulunmuyor.</p>}</div>
    </section>

    <section id="portfolio" className="card scroll-mt-32 mt-6 overflow-hidden"><div className="section-toolbar border-b border-[var(--rule)] px-5 py-4"><div><p className="eyebrow">Portföy yönetimi</p><h2 className="section-heading mt-1">Son güncellenen çalışmalar</h2><p className="mt-1 text-xs text-[var(--muted-2)]">Durum, metodoloji, ilerleme ve açık güvence borcunu birlikte gösterir.</p></div><Link href="/gorevler" className="btn btn-secondary">Tüm görevleri aç</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-sm"><thead className="border-b border-[var(--rule-strong)] bg-[var(--surface-sunk)] text-left text-[11px] uppercase tracking-[0.05em] text-[var(--muted)]"><tr><th className="px-5 py-3">Çalışma</th><th className="px-3 py-3">Metodoloji</th><th className="px-3 py-3">Yaşam döngüsü</th><th className="px-3 py-3">İlerleme</th><th className="px-3 py-3">Açıklar</th><th className="px-5 py-3 text-right">İşlem</th></tr></thead><tbody className="divide-y divide-[var(--rule)]">{workspaces.slice(0,30).map((workspace)=><tr key={workspace.id} className="hover:bg-[var(--surface-sunk)]"><td className="max-w-md px-5 py-3"><strong className="block truncate">{workspace.problemDescription}</strong><small className="text-[var(--muted-2)]">{new Date(workspace.updatedAt).toLocaleString('tr-TR')}</small></td><td className="px-3 py-3">{workspace.methodologyName}</td><td className="px-3 py-3"><span className="tag state-idle">{closureLabel[workspace.closureStatus]}</span></td><td className="px-3 py-3 tabular-nums">{workspace.doneSteps}/{workspace.totalSteps}</td><td className="px-3 py-3 text-xs text-[var(--muted)]">{workspace.openActions} aksiyon · {workspace.unverifiedClaims} iddia</td><td className="px-5 py-3 text-right"><Link className="font-medium underline decoration-[var(--rule-strong)] underline-offset-[3px] hover:decoration-[var(--ink)]" href={`/workspace/${workspace.id}`}>İncele</Link></td></tr>)}{!workspaces.length&&<tr><td colSpan={6} className="p-10 text-center text-[var(--muted-2)]">Henüz çalışma bulunmuyor.</td></tr>}</tbody></table></div>{workspaces.length>30&&<p className="border-t border-[var(--rule)] px-5 py-3 text-xs text-[var(--muted-2)]">İlk 30 kayıt gösteriliyor. Tam liste için Çalışmalar ekranını kullanın.</p>}</section>

    <section id="diagnosis" className="scroll-mt-32 mt-6 grid gap-5 xl:grid-cols-2"><div className="card p-5"><p className="eyebrow">Soru kataloğu</p><h2 className="section-heading mt-1">{FEATURE_KEYS.length} teşhis değişkeni</h2><p className="mt-1 text-xs text-[var(--muted-2)]">Sorular sürümlü kaynak kodundan gelir; burada hangi karar sinyalinin kullanıcıya nasıl sorulduğunu denetleyin.</p><div className="mt-4 max-h-[620px] space-y-2 overflow-y-auto pr-1">{FEATURE_KEYS.map((key)=><details key={key} className="subtle-panel py-3"><summary className="cursor-pointer text-sm font-semibold">{FEATURE_META[key].label}<span className="ml-2 font-mono text-[10px] font-normal text-[var(--muted-2)]">{key}</span></summary><p className="mt-2 text-xs leading-5 text-[var(--ink-soft)]">{FEATURE_META[key].questionTheme}</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><span className="rounded-lg bg-[var(--st-ok-bg)] p-2 text-[11px] text-[var(--st-ok)]">Evet: {FEATURE_META[key].traceWhenTrue}</span><span className="rounded-lg bg-[var(--surface-mark)] p-2 text-[11px] text-[var(--ink-soft)]">Hayır: {FEATURE_META[key].traceWhenFalse}</span></div></details>)}</div></div>
      <div className="card p-5"><p className="eyebrow">Kural yönetişimi</p><h2 className="section-heading mt-1">{RULES.length} kural · {ruleEffects} metodoloji etkisi</h2><p className="mt-1 text-xs text-[var(--muted-2)]">Canlı ağırlıklar yalnız testli kaynak sürümüyle değiştirilir. Bu ekran karar motorunun okunabilir envanteridir.</p><div className="mt-4 max-h-[620px] space-y-2 overflow-y-auto pr-1">{RULES.map((rule)=><details key={rule.id} className="subtle-panel py-3"><summary className="cursor-pointer text-sm font-semibold"><span className="mr-2 font-mono text-xs text-[var(--ink)]">{rule.id}</span>{rule.because}</summary><p className="mt-2 text-[11px] text-[var(--muted)]">Okunan sinyaller: {rule.reads.map((key)=>FEATURE_META[key].label).join(', ')}</p><div className="mt-2 flex flex-wrap gap-1.5">{Object.entries(rule.effect).map(([methodology,score])=><span key={methodology} className={`px-2 py-1 text-[10px] font-semibold ${(score??0)>0?'bg-[var(--st-ok-bg)] text-[var(--st-ok)]':'bg-[var(--st-risk-bg)] text-[var(--st-risk)]'}`}>{METHODOLOGY_META[methodology as keyof typeof METHODOLOGY_META].shortName} {Number(score)>0?'+':''}{score}</span>)}</div></details>)}</div></div>
      <div className="card p-5 xl:col-span-2"><p className="eyebrow">Sonuçlandırma politikası</p><h2 className="section-heading mt-1">Erken ve zayıf öneriyi engelleyen eşikler</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(DEFAULT_STOP_POLICY).map(([key,value])=><div key={key} className="subtle-panel"><p className="font-mono text-[10px] text-[var(--muted-2)]">{key}</p><strong className="mt-1 block text-xl">{value}</strong></div>)}</div></div>
    </section>

    <section id="playbooks" className="card scroll-mt-32 mt-6 p-5"><div className="section-toolbar"><div><p className="eyebrow">Metodoloji kapsamı</p><h2 className="section-heading mt-1">{METHODOLOGIES.length} yöntem · {playbookSteps} adım · {playbookFields} yapılandırılmış alan</h2><p className="mt-1 text-xs text-[var(--muted-2)]">Her çalışma alanının sunduğu profesyonel yürütme şablonu.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{METHODOLOGIES.map((methodology)=>{const book=PLAYBOOKS[methodology];const fields=book.steps.reduce((sum,step)=>sum+step.fields.length,0);return <Link href={`/diagnoz`} key={methodology} className="card card-interactive p-4"><div className="flex items-center justify-between gap-2"><strong>{METHODOLOGY_META[methodology].shortName}</strong><span className="text-xs text-[var(--muted-2)]">{book.steps.length} adım · {fields} alan</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[var(--muted)]">{book.intro}</p></Link>})}</div></section>

    <section id="system" className="scroll-mt-32 mt-6 grid gap-5 lg:grid-cols-2"><div className="card p-5"><p className="eyebrow">Çalışma ortamı</p><h2 className="section-heading mt-1">Yapılandırma sağlığı</h2><div className="mt-4 space-y-3"><ConfigRow label="Üyelik sistemi" ready={accountAuthEnabled()} readyText="Bireysel ve şirket hesapları etkin" missingText="Eski yerel erişim modu"/><ConfigRow label="Ayrı platform yöneticisi" ready={Boolean(adminPassword())} readyText="ADMIN_PASSWORD ile ayrıştırıldı" missingText="Platform yöneticisi parolası eksik"/><ConfigRow label="Kalıcı veri tabanı" ready={process.env.PERSISTENCE==='prisma'} readyText="PostgreSQL / Prisma" missingText="Üyelik sistemi için Prisma gerekli"/><ConfigRow label="AI sağlayıcısı" ready={Boolean(process.env.AI_PROVIDER&&process.env.AI_PROVIDER!=='none')} readyText={process.env.AI_PROVIDER??'Etkin'} missingText="Deterministik mod"/></div></div><div className="card p-5"><p className="eyebrow">Erişim modeli</p><h2 className="section-heading mt-1">Bireysel ve şirket hesapları</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Bireysel kullanıcı yalnız kendi portföyünü yönetir. Şirket sahibi çalışanlarını, rollerini ve şirket çalışmalarını şirket panelinden izler. Platform admini ise ürünün teknik yönetişimi için ayrı tutulur.</p><div className="subtle-panel mt-4 text-[11px] leading-relaxed"><strong>Yetki ilkesi:</strong> Çalışan kendi kayıtlarını, ekip yöneticisi şirket portföyünü yönetir; izleyici rolü değişiklik yapamaz. Kullanıcı askıya alındığında aktif oturumları sonlandırılır.</div></div></section>
  </main>;
}

function AdminMetric({label,value,detail,tone}:{label:string;value:number;detail:string;tone:'indigo'|'red'|'amber'|'green'}) {
  const map={indigo:'info',red:'risk',amber:'warn',green:'ok'} as const;
  return <Readout label={label} value={value} detail={detail} tone={map[tone]}/>;
}
function ConfigRow({label,ready,readyText,missingText}:{label:string;ready:boolean;readyText:string;missingText:string}) { return <div className="record-row flex items-center justify-between gap-4"><div><strong className="block text-sm">{label}</strong><span className="text-xs text-[var(--muted-2)]">{ready?readyText:missingText}</span></div><span className={`tag ${ready?'state-ok':'state-warn'}`}>{ready?'Hazır':'Dikkat'}</span></div> }
