import {z} from "zod";import {ADVANCED_TOOLS} from "@/domain/advanced-analysis";
const s=z.string(), sn=s.nullable(), ss=z.array(s), row=z.record(s,s), id=z.object({id:s.min(1)});
export const evidenceSchema=id.extend({title:s,source:s,finding:s,stepKey:sn.optional(),claimId:sn.optional(),recordedAt:s});
const action=id.partial().extend({action:s.min(1),owner:sn,status:z.enum(["OPEN","IN_PROGRESS","IMPLEMENTED","EFFECTIVENESS_DUE","EFFECTIVE","INEFFECTIVE","DONE"]),dueDate:sn.optional(),targetCauseId:sn.optional(),successMetric:s.optional(),baseline:s.optional(),target:s.optional(),actual:s.optional(),verificationDueDate:sn.optional(),evidenceIds:ss.optional()});
const document=id.extend({type:z.enum(["STANDARD_WORK","CONTROL_PLAN","PFMEA","DFMEA","MAINTENANCE_PLAN","INSPECTION_INSTRUCTION","OPL","COMPETENCY_RECORD"]),title:s,revision:s,status:z.enum(["DRAFT","IN_REVIEW","APPROVED","SUPERSEDED"]),owner:s,approver:s,effectiveDate:sn,changeSummary:s,evidenceIds:ss,relatedWorkspaceId:s});
const containment=id.extend({purpose:s,scope:s,startedAt:s,owner:s,effectivenessMetric:s,currentResult:s,costOrBurden:s,removalCriteria:s,status:z.enum(["ACTIVE","VERIFYING","REMOVED","TRANSFERRED"]),removalApprovedBy:s,removedAt:sn,permanentActionId:sn,evidenceIds:ss});
const weak=id.extend({type:z.enum(["HUMAN_OBSERVATION","PROCESS_MEASUREMENT","MICRO_STOP","TEMPORARY_INTERVENTION","REMEASUREMENT","SORTING","WIP","SCHEDULE_CHANGE","OVERTIME","MAINTENANCE_DEFERRAL","PSYCHOLOGICAL_SAFETY"]),description:s,source:s,detectedAt:s,status:z.enum(["NEW","TRIAGED","VERIFYING","DISMISSED","WATCHING","CASE_OPENED"]),hypothesis:s,verificationTask:s,owner:s,dueDate:sn,evidenceIds:ss,linkedWorkspaceId:sn});
const advanced=id.extend({tool:z.enum(ADVANCED_TOOLS),title:s,status:z.enum(["DRAFT","IN_PROGRESS","REVIEW","COMPLETED"]),decisionPoint:s,hypothesis:s,fields:row,rows:z.array(row),conclusion:s,evidenceIds:ss});
const jsonValue:z.ZodType<unknown>=z.lazy(()=>z.union([s,z.number(),z.boolean(),z.null(),z.array(jsonValue),z.record(s,jsonValue)]));
// Bazı domain kayıtları `id`, bazıları ise doğal anahtar (`dimension`, `findingId`)
// kullanır. Ortak JSON nesnesinde id'yi zorunlu tutmak QMS ve red-team autosave'ini
// reddediyordu. Kimlik gerektiren kritik nesneler yukarıdaki özel şemalarda ayrıca
// doğrulanır; heterojen destek koleksiyonlarında id varsa boş olamaz.
const genericId=id.partial().catchall(jsonValue);
const approval=z.object({role:z.enum(["QUALITY","PROCESS_OWNER","CUSTOMER_REP"]),name:s,status:z.enum(["PENDING","APPROVED","REJECTED"]),comment:s,decidedAt:sn.optional()});
export const workspacePatchSchema=z.object({
 steps:z.array(z.object({key:s,status:z.enum(["PENDING","IN_PROGRESS","READY","VERIFIED","SKIPPED","DONE"]),values:z.record(s,z.union([s,z.array(row)]))})).optional(),actions:z.array(action).optional(),
 evidence:z.array(evidenceSchema).optional(),claims:z.array(id.extend({statement:s,kind:z.enum(["HYPOTHESIS","ROOT_CAUSE","CONCLUSION"]),status:z.enum(["CLAIMED","VERIFIED","REJECTED"]),stepKey:sn.optional(),evidenceIds:ss,counterfactual:s.optional()})).optional(),
 metrics:z.array(genericId).optional(),links:z.array(genericId).optional(),approvals:z.array(approval).optional(),monitoring:z.object({metric:s,trigger:s,reviewDate:sn,owner:s,result:z.literal("PENDING")}).nullable().optional(),specialty:z.record(s,z.unknown()).optional(),redTeamReviews:z.array(genericId).optional(),horizontalTargets:z.array(genericId).optional(),attachments:z.array(genericId).optional(),
 closureStatus:z.enum(["OPEN","CLOSURE_CANDIDATE","MONITORING","CLOSED","REOPENED"]).optional(),closedAt:sn.optional(),reopenCount:z.number().int().nonnegative().optional(),
 systemDocuments:z.array(document).optional(),containmentControls:z.array(containment).optional(),learningDecision:z.object({summary:s,decision:z.enum(["PENDING","DOCUMENT_UPDATED","NO_UPDATE_REQUIRED"]),documentIds:ss,rationale:s,owner:s,approvedBy:s,decidedAt:sn}).optional(),weakSignals:z.array(weak).optional(),dailyManagement:z.array(genericId).optional(),kaizenExperiments:z.array(genericId).optional(),oplLessons:z.array(genericId).optional(),controlBurden:z.array(genericId).optional(),contextContract:z.object({purpose:s,scope:s,outOfScope:s,successMetric:s,methodRole:s,pivotCondition:s,misuseRisk:s,undesiredBehavior:s,owner:s,approvedBy:s}).optional(),systemBehaviorAnalyses:z.array(genericId).optional(),qmsHealth:z.array(genericId).optional(),gembaBehaviorMap:z.array(genericId).optional(),benchmarkReferences:z.array(genericId).optional(),capacityScenarios:z.array(genericId).optional(),sopScenarios:z.array(genericId).optional(),lineBalanceStudies:z.array(genericId).optional(),advancedAnalyses:z.array(advanced).optional(),report:sn.optional(),
 recommendationFeedback:z.object({decision:z.enum(["PENDING","ACCEPTED","REJECTED","OVERRIDDEN"]),recommendedMethodology:s,selectedMethodology:s,reason:s,reviewedAt:sn,outcome:z.enum(["PENDING","SUCCESS","PARTIAL","FAILED"]),outcomeNote:s,outcomeAt:sn}).optional(),
 methodSelectionContext:z.object({customerMandate:s,regulatoryMandate:s,existingCaseSystem:s,requiredFormat:s,teamCompetence:z.enum(["UNKNOWN","LOW","MEDIUM","HIGH"]),facilitatorAvailable:z.boolean(),containmentHours:z.number().nonnegative().nullable(),resolutionDays:z.number().nonnegative().nullable(),availablePeople:z.number().int().nonnegative().nullable(),managementExpectation:s,resourceConstraint:s}).optional(),
 fieldPilot:z.object({status:z.enum(["NOT_PLANNED","PLANNED","RUNNING","COMPLETED","ABORTED"]),site:s,line:s,owner:s,participants:s,startedAt:sn,completedAt:sn,baselineCycleHours:z.number().nonnegative().nullable(),actualCycleHours:z.number().nonnegative().nullable(),baselineRecurrenceRate:z.number().nonnegative().nullable(),actualRecurrenceRate:z.number().nonnegative().nullable(),observationDays:z.number().int().nonnegative().nullable(),duplicateEntryMinutes:z.number().nonnegative().nullable(),frictionPoints:s,userFeedback:s,workarounds:s,result:z.enum(["PENDING","POSITIVE","MIXED","NEGATIVE"])}).optional(),
 externalSystemLinks:z.array(z.object({id:s.min(1),system:z.enum(["SAP_QM","SAP_PM","MES","QMS_CAPA","ERP","DATA_WAREHOUSE","OTHER"]),externalId:s,url:s,ownership:z.enum(["EXTERNAL_MASTER","MDI_MASTER","SHARED"]),syncStatus:z.enum(["NOT_CONFIGURED","MANUAL","SYNCED","ERROR"]),lastSyncedAt:sn,notes:s})).optional(),
}).strict();
